### ISSUE TITLE
Mod to support CHT8310?

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [RobTillaart/CHT8305#14]
Hi - 

I am repurposing a generic white label Tuya sensor by changing the BK7231 module out for an ESP32-C3 module, and running custom Ardunio code. The sensors I have use a CHT83**10** chip.

I found your work here, and wonder if with the information in [this link](https://github.com/openshwprojects/OpenBK7231T_App/issues/983#issuecomment-1868112898) you would be able to modify the calculation part to support the 8310 sensor ?  In that thread are [PDF extracts](https://github.com/openshwprojects/OpenBK7231T_App/issues/983#issuecomment-1842719866) that make It seem like the numbers coming from the sensor are different to the 8305 and "just" need some different math (hopefully it's that simple!)

I also found [this code contribution.](https://github.com/artin961/OpenBK7231T_App/commit/0403abdfbb9912272be32d33177aaaf6b974eb2d)

Naturally i would test and report back both the 8310 results and use on the ESP32 if you were able to do this.

Thanks!

**Comment by YouCanNotBeSerious** [comment]
Found the [full datasheet here](https://pvvx.github.io/THB2/CHT8310.Advanced.Datasheet_Ver1.0.20230407.pdf) - there are plenty of 4 page versions around without the protocol detail...

**Comment by RobTillaart** [comment]
Thanks for the question, 
I will look into this tomorrow if time permits.

There are two possible ways, as a derived class or a stand alone project, depending if they are more or less close. 
To be continued

**Comment by RobTillaart** [comment]
### Analysis
I had a quick look and the register maps are quite different

**CHT8305** datasheet (oct 2017 - rev 1.1)
![image](https://github.com/RobTillaart/CHT8305/assets/462844/0a5fa8d8-5286-4bd2-8002-86243a29f679)

**CHT8310** datasheet (april 2023 - rev 1.0)
![image](https://github.com/RobTillaart/CHT8305/assets/462844/e7ac3fa0-9496-48e4-9664-fe5275618274)

Temperature and humidity registers are on the same index (but different math) 
The other registers do not match.

### Conclusion
The sensors are too different to make a derived class.
Patching the 8305 library with only different math for T and H will result in problems with other registers
causing more patches / maintenance.

So the only solution is to design and implement a separate library for the **CHT8310**.
The interfaces could be kept similar where possible of course.

**Comment by RobTillaart** [comment]
note: 
There is a whole family CHT83xx - there might be compatible ones.
![image](https://github.com/RobTillaart/CHT8305/assets/462844/1550db22-68c0-4afd-a92e-ffbf98dc55c5)

**Comment by RobTillaart** [comment]
A minimal class for the CHT8310 would 
- read Temperature
- read Humidity
- read manufacturer ID (CHT8305 = 5950, CHT8310 = 5959) 
- no further settings etc

**Comment by RobTillaart** [comment]
Created such a minimal class - https://github.com/RobTillaart/CHT8310 
(under development)

**Comment by RobTillaart** [comment]
@YouCanNotBeSerious 
Released a 0.1.0 version of the CHT8310 library - https://github.com/RobTillaart/CHT8310
It is pretty minimal and should get you started. 
If there are problems, please open an issue under that repo.

**Comment by YouCanNotBeSerious** [comment]
> @YouCanNotBeSerious Released a 0.1.0 version of the CHT8310 library - https://github.com/RobTillaart/CHT8310 It is pretty minimal and should get you started. If there are problems, please open an issue under that repo.

Wow! Thanks - I will test as soon as I ...ahem... repair my temperature sensor hardware (don't ask!).  I also have more units arriving any time now if I can't undo my mistake :-)

**Comment by RobTillaart** [comment]
@YouCanNotBeSerious 

Welcome, it is an interesting sensor and by stripping (a copy) of the CHT8305 I had 50% in place.
Still it took a few hours to get it to (beta?) release level, and now there is a reasonable base to start the tests.

I close the issue here, so please open an issue under the cht8310 repo to continue the discussion.
